title: ihD | Global Technology Consultant
email: IHD@ihd-hk.com
description: > # this means to ignore newlines until "baseurl:"
  ihD Ltd is a Hong Kong-registered Private Limited Company, specialising in IT,
  ELV & Security, and Audio-Visual Systems, as well as Mechanical & Architectural
  Acoustics, design and Consultancy. Our company is not involved in any way in the
  supply of equipment nor in installation. We focus instead on Design, Consultancy,
  and Project Management, allowing us to remain independant, specifying equipment
  and systems most suited to our clients technical and budgetary needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: ihd-hk/ihd-hk.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  math_engine: mathjax # Forced Default from GH Pages
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - assets/bootstrap
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

# Navigation
navigation:
  en:
  - text: Home
    url: '/'
  - text: About
    url: '/about.html'
  - text: Services
    url: '/services.html'
  - text: Portfolio
    url: '/portfolio.html'
  - text: Contact
    url: '/contact.html'
  - text: 中文
    url: '/ch/'
  ch:
  - text: 主页
    url: '/ch/'
  - text: 关于德勤
    url: '/ch/about.html'
  - text: 服务范围
    url: '/ch/services.html'
  - text: 项目案例
    url: '/ch/portfolio.html'
  - text: 联系方式
    url: '/ch/contact.html'


# CANNOT CHANGE THESE
lsi: false
safe: true
source: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
# kramdown:
#   math_engine: mathjax
